"""Describe delegated methods, including edits that return the underlying model."""

from collections.abc import Sequence
from typing import Any

from sklearn.base import BaseEstimator, ClassifierMixin

from .._typing import ArrayLike, FloatArray, LabelArray, MonotoneConstraints, SelfT
from .compact import CompactTreeBooster
from .explain import InterpretableSumMixin
from .smalltrees import FIGSClassifier

_BudgetModel = FIGSClassifier | CompactTreeBooster

class BudgetClassifier(InterpretableSumMixin, ClassifierMixin, BaseEstimator):
    max_splits: int
    model_: FIGSClassifier | CompactTreeBooster
    classes_: LabelArray
    n_features_in_: int
    feature_names_in_: LabelArray

    def __init__(self, max_splits: int = ...) -> None: ...
    def fit(self: SelfT, X: ArrayLike, y: ArrayLike,
            sample_weight: ArrayLike | None = ...) -> SelfT: ...
    def predict_proba(self, X: ArrayLike) -> FloatArray: ...
    def predict(self, X: ArrayLike) -> LabelArray: ...
    def decision_function(self, X: ArrayLike) -> FloatArray: ...

    def prune(self, tree: int, node: int, X: ArrayLike | None = ...,
              sample_weight: ArrayLike | None = ...) -> _BudgetModel: ...
    def set_cut(self, tree: int, node: int, feature: int | str, threshold: float) -> float: ...
    def split_leaf(self, tree: int, leaf: int, feature: int | str,
                   threshold: float) -> tuple[int, int, float]: ...
    def add_stump(self, feature: int | str, threshold: float, left_value: float = ...,
                  right_value: float = ...) -> tuple[int, float]: ...
    def drop_tree(self, tree: int) -> _BudgetModel: ...
    def merge_duplicates(self) -> int: ...
    def set_leaf_value(self, tree: int, node: int, value: float) -> _BudgetModel: ...
    def refit_leaves(self, X: ArrayLike, y: ArrayLike,
                     sample_weight: ArrayLike | None = ..., lam: float | None = ...,
                     sweeps: int = ..., trees: Sequence[int] | None = ...,
                     refit_base: bool = True,
                     monotone: MonotoneConstraints | None = ...) -> _BudgetModel: ...
    def monotone_violations(self, feature: int | str, increasing: bool = ...,
                            tol: float = ...) -> list[tuple[int, int, int, float]]: ...
    def enforce_monotone(self, monotone: MonotoneConstraints) -> _BudgetModel: ...
    def cut_alternatives(self, X: ArrayLike, y: ArrayLike, tree: int, node: int, *,
                         sample_weight: ArrayLike | None = ..., top: int = ...,
                         epsilon: float = ..., lam: float | None = ...,
                         sweeps: int = ...) -> list[dict[str, Any]]: ...
